## Numpy Practice Day1

#### Superior Data Type
* String
* Float
* Int
* Bool

In [2]:
import numpy as np

In [4]:
array = np.asarray([1,2])

In [5]:
type(array)

numpy.ndarray

In [10]:
array.shape

(2,)

In [14]:
array = np.asarray([[1,2],[3,4]])

In [15]:
array

array([[1, 2],
       [3, 4]])

In [16]:
array.shape

(2, 2)

In [17]:
array.dtype

dtype('int32')

In [18]:
array = np.asarray([[1,2],[3,4.9]])

In [19]:
array.dtype

dtype('float64')

In [20]:
array

array([[1. , 2. ],
       [3. , 4.9]])

In [21]:
array = np.asarray([['1',2],[3,4]])

In [22]:
array

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [23]:
array.dtype

dtype('<U1')

In [27]:
np.__version__


'1.16.2'

In [28]:
np.__path__

['C:\\Users\\Ajayk\\Anaconda3\\lib\\site-packages\\numpy']

In [30]:
a=np.asarray([[1,2],[3,4]])

In [31]:
a+10

array([[11, 12],
       [13, 14]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
array =  array.astype('int')

In [34]:
array

array([[1, 2],
       [3, 4]])

In [35]:
b=a+10

In [36]:
b

array([[11, 12],
       [13, 14]])

In [37]:
b+array

array([[12, 14],
       [16, 18]])

In [38]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [39]:
b-array

array([[10, 10],
       [10, 10]])

In [40]:
b/2

array([[5.5, 6. ],
       [6.5, 7. ]])

In [41]:
b**2

array([[121, 144],
       [169, 196]], dtype=int32)

In [42]:
b

array([[11, 12],
       [13, 14]])

In [45]:
array_3d =  np.array([[(1,2,3),(3,4,3)],[(5,6,3),(7,8,3)]])

In [46]:
array_3d.shape

(2, 2, 3)

In [47]:
array_3d

array([[[1, 2, 3],
        [3, 4, 3]],

       [[5, 6, 3],
        [7, 8, 3]]])

In [57]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [56]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [58]:
b

array([[11, 12],
       [13, 14]])

In [61]:
b.reshape(4,1)

array([[11],
       [12],
       [13],
       [14]])

In [60]:
b.flatten()

array([11, 12, 13, 14])