## Numpy Practice Day1

#### Superior Data Type
* String
* Float
* Int
* Bool

In [1]:
import numpy as np

In [4]:
array = np.asarray([1,2])

In [5]:
type(array)

numpy.ndarray

In [10]:
array.shape

(2,)

In [14]:
array = np.asarray([[1,2],[3,4]])

In [15]:
array

array([[1, 2],
       [3, 4]])

In [16]:
array.shape

(2, 2)

In [17]:
array.dtype

dtype('int32')

In [18]:
array = np.asarray([[1,2],[3,4.9]])

In [19]:
array.dtype

dtype('float64')

In [20]:
array

array([[1. , 2. ],
       [3. , 4.9]])

In [21]:
array = np.asarray([['1',2],[3,4]])

In [22]:
array

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [23]:
array.dtype

dtype('<U1')

In [27]:
np.__version__


'1.16.2'

In [28]:
np.__path__

['C:\\Users\\Ajayk\\Anaconda3\\lib\\site-packages\\numpy']

In [30]:
a=np.asarray([[1,2],[3,4]])

In [31]:
a+10

array([[11, 12],
       [13, 14]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
array =  array.astype('int')

In [34]:
array

array([[1, 2],
       [3, 4]])

In [35]:
b=a+10

In [36]:
b

array([[11, 12],
       [13, 14]])

In [37]:
b+array

array([[12, 14],
       [16, 18]])

In [38]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [39]:
b-array

array([[10, 10],
       [10, 10]])

In [40]:
b/2

array([[5.5, 6. ],
       [6.5, 7. ]])

In [41]:
b**2

array([[121, 144],
       [169, 196]], dtype=int32)

In [42]:
b

array([[11, 12],
       [13, 14]])

In [45]:
array_3d =  np.array([[(1,2,3),(3,4,3)],[(5,6,3),(7,8,3)]])

In [46]:
array_3d.shape

(2, 2, 3)

In [47]:
array_3d

array([[[1, 2, 3],
        [3, 4, 3]],

       [[5, 6, 3],
        [7, 8, 3]]])

In [57]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [56]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [58]:
b

array([[11, 12],
       [13, 14]])

In [61]:
b.reshape(4,1)

array([[11],
       [12],
       [13],
       [14]])

In [60]:
b.flatten()

array([11, 12, 13, 14])

### Numpy Day 2

In [2]:
a=np.asarray([2,3])

In [3]:
a+10

array([12, 13])

In [4]:
b= np.asarray([4,5])

In [7]:
a1= np.array([[1,2],[3,4]])

In [10]:
a2= np.array([[3,4],[5,6]])

For horizontal stack no of cols same,for vstack no of rows same

In [11]:
np.hstack((a1,a2))

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [12]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [13]:
np.hsplit(a1,2)

[array([[1],
        [3]]), array([[2],
        [4]])]

In [14]:
np.vsplit(a1,2)

[array([[1, 2]]), array([[3, 4]])]

In [27]:
a= np.random.normal(30,12,(1000,1000))

In [31]:
b=np.random.chisquare(30,12)

In [28]:
a.mean()

30.000654893067438

In [30]:
a.std()

11.999320526978954

In [32]:
b.mean()

34.309412415508014

In [33]:
b.std()

10.928825390232843

In [34]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Linspace - startpnt end pnt how many numbers

In [39]:
np.linspace(1,10,5,endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [42]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
a= np.zeros((4,4))

In [45]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
a[::2,1::2]=1

In [47]:
a[1::2,::2]=1

In [48]:
a

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [50]:
a.mean()

0.5

In [51]:
a=np.asarray([[1,2],[3,4]])

In [52]:
b=np.asarray([[5,6],[7,8]])

In [53]:
a*b

array([[ 5, 12],
       [21, 32]])

In [54]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [76]:
np.diag((1,2,3),k=0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [77]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [79]:
np.linalg.det(a)

-2.0000000000000004

In [80]:
a

array([[1, 2],
       [3, 4]])

In [82]:
deta=np.linalg.inv(a)

In [83]:
np.dot(a,deta)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [86]:
np.cov(a)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [97]:
a=np.asarray([[0,0],[1,1],[2,2]])

In [93]:
a

array([[0, 2],
       [1, 1],
       [2, 0]])

In [98]:
np.cov(a.T)

array([[1., 1.],
       [1., 1.]])