In [68]:
import numpy as np
from sklearn import decomposition
from sklearn import datasets

In [69]:
iris = datasets.load_iris()
x= iris.data
y=iris.target

In [70]:
x.shape

(150, 4)

In [71]:
pca = decomposition.PCA(n_components=3)
pca.fit(x)
x= pca.transform(x)

In [72]:
x

array([[-2.68412563,  0.31939725, -0.02791483],
       [-2.71414169, -0.17700123, -0.21046427],
       [-2.88899057, -0.14494943,  0.01790026],
       [-2.74534286, -0.31829898,  0.03155937],
       [-2.72871654,  0.32675451,  0.09007924],
       [-2.28085963,  0.74133045,  0.16867766],
       [-2.82053775, -0.08946138,  0.25789216],
       [-2.62614497,  0.16338496, -0.02187932],
       [-2.88638273, -0.57831175,  0.02075957],
       [-2.6727558 , -0.11377425, -0.19763272],
       [-2.50694709,  0.6450689 , -0.07531801],
       [-2.61275523,  0.01472994,  0.10215026],
       [-2.78610927, -0.235112  , -0.20684443],
       [-3.22380374, -0.51139459,  0.06129967],
       [-2.64475039,  1.17876464, -0.15162752],
       [-2.38603903,  1.33806233,  0.2777769 ],
       [-2.62352788,  0.81067951,  0.13818323],
       [-2.64829671,  0.31184914,  0.02666832],
       [-2.19982032,  0.87283904, -0.12030552],
       [-2.5879864 ,  0.51356031,  0.21366517],
       [-2.31025622,  0.39134594, -0.239

`Manually

In [73]:
x= iris.data
y=iris.target

In [74]:
np.cov(x.T)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [75]:
mean = x.mean(axis=0)

In [76]:
mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [77]:
x_std = x-mean

In [78]:
x_std

array([[-7.43333333e-01,  4.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01, -5.73333333e-02, -2.35800000e+00,
        -9.99333333e-01],
       [-1.14333333e+00,  1.42666667e-01, -2.45800000e+00,
        -9.99333333e-01],
       [-1.24333333e+00,  4.26666667e-02, -2.25800000e+00,
        -9.99333333e-01],
       [-8.43333333e-01,  5.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-4.43333333e-01,  8.42666667e-01, -2.05800000e+00,
        -7.99333333e-01],
       [-1.24333333e+00,  3.42666667e-01, -2.35800000e+00,
        -8.99333333e-01],
       [-8.43333333e-01,  3.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.44333333e+00, -1.57333333e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01,  4.26666667e-02, -2.25800000e+00,
        -1.09933333e+00],
       [-4.43333333e-01,  6.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.04333333e+00,  3.42666667e-01, -2.15800000e+00,
      

In [79]:
cov = np.cov(x_std.T)

In [80]:
cov

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [81]:
en_v,en_vect = np.linalg.eig(cov)

In [82]:
en_v

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [83]:
tm = en_vect[:,:3]

In [84]:
tm

array([[ 0.36138659, -0.65658877, -0.58202985],
       [-0.08452251, -0.73016143,  0.59791083],
       [ 0.85667061,  0.17337266,  0.07623608],
       [ 0.3582892 ,  0.07548102,  0.54583143]])

In [85]:
x_trans = np.dot(x_std,tm)

In [86]:
x_trans

array([[-2.68412563, -0.31939725, -0.02791483],
       [-2.71414169,  0.17700123, -0.21046427],
       [-2.88899057,  0.14494943,  0.01790026],
       [-2.74534286,  0.31829898,  0.03155937],
       [-2.72871654, -0.32675451,  0.09007924],
       [-2.28085963, -0.74133045,  0.16867766],
       [-2.82053775,  0.08946138,  0.25789216],
       [-2.62614497, -0.16338496, -0.02187932],
       [-2.88638273,  0.57831175,  0.02075957],
       [-2.6727558 ,  0.11377425, -0.19763272],
       [-2.50694709, -0.6450689 , -0.07531801],
       [-2.61275523, -0.01472994,  0.10215026],
       [-2.78610927,  0.235112  , -0.20684443],
       [-3.22380374,  0.51139459,  0.06129967],
       [-2.64475039, -1.17876464, -0.15162752],
       [-2.38603903, -1.33806233,  0.2777769 ],
       [-2.62352788, -0.81067951,  0.13818323],
       [-2.64829671, -0.31184914,  0.02666832],
       [-2.19982032, -0.87283904, -0.12030552],
       [-2.5879864 , -0.51356031,  0.21366517],
       [-2.31025622, -0.39134594, -0.239

In [87]:
x_re = np.dot(x_trans,tm.T)+mean

In [88]:
x_re

array([[5.09928623, 3.50072335, 1.40108561, 0.1982949 ],
       [4.86875839, 3.03166108, 1.4475168 , 0.12536791],
       [4.69370023, 3.20638436, 1.30958161, 0.18495067],
       [4.6238432 , 3.07583667, 1.46373578, 0.25695828],
       [5.0193263 , 3.58041421, 1.37060574, 0.24616799],
       [5.40763506, 3.89226243, 1.68838749, 0.41823916],
       [4.61518853, 3.38460754, 1.37689906, 0.33628341],
       [5.0142909 , 3.38551722, 1.47826432, 0.23413908],
       [4.40843762, 2.89144909, 1.38716683, 0.22015637],
       [4.91776048, 3.08200106, 1.47298727, 0.14242745],
       [5.40473859, 3.69519778, 1.49279285, 0.21131988],
       [4.84933564, 3.35000195, 1.52496316, 0.31785635],
       [4.80248854, 2.99747805, 1.39621507, 0.10594478],
       [4.3068397 , 2.99306846, 1.08959718, 0.11633915],
       [5.74977137, 4.05090303, 1.27639503, 0.08001041],
       [5.69793307, 4.40209468, 1.50314369, 0.39506238],
       [5.34708184, 3.95362867, 1.38048567, 0.27358547],
       [5.0755093 , 3.52481952,

In [89]:
error = ((x-x_re)**2).mean()

In [90]:
error

0.005919048088406611